### ISSUE TITLE
后端开源

### ISSUE THREAD

**Issue by IOSYuan** [Satoing/sakana-acg#3]
如果后端也开源就更好了

**Comment by Satoing** [comment]
其实后端就是一个python爬虫，只有一个文件，而且写的很烂😂
涉及到的代码就是下面这些，http框架用的是python的flask。
```python
@app.route('/acg/<id>')
def get_infos(id):
    base_url = 'http://agedm1.com/acg/'
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
    }
    res = requests.get(url=base_url+id+'/', headers=header)
    res.encoding = 'utf-8'
    tree = etree.HTML(res.text)
    intro = tree.xpath("//*[@class='detail_imform_desc_pre']/p/text()")[0]
    title = tree.xpath("//*[@class='detail_imform_name']/text()")[0]
    playlist = tree.xpath("//*[@id='container']/div[5]/script[2]/@src")[0]
    img = tree.xpath('//*[@id="container"]/div[4]/div[1]/div/img/@data-original')[0]
    tags = tree.xpath('//*[@id="container"]/div[4]/div[2]/div/div/ul/li[5]/span[2]/a/text()')
    print(tags)
    
    info = {'title': title, 'intro': intro, 'playlist': playlist, 'img': img, 'tags': tags}
    
    return jsonify(info), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}

@app.route('/acg/search')
def search():
    q = request.args.get('q')
    url = 'http://159.75.0.62:11234/ssszz.php?top=10&q={q}&dect=0'
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
    }
    query = {'top':10, 'q': q, 'dect': 0}
    res = requests.get(url=url, headers=header, params=query)
    res.encoding = 'utf-8'
    return res.text, 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}

@app.route('/bangumi')
def bangumi():
    q = request.args.get('q')
    if(len(q) >= 7): q = q[:math.ceil(len(q)//2)]
    if(re.match('.*?第.{0,2}', q)):
        q = re.search('(.*?)第.{0,2}', q).group(1)
    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'
    }
    # 获取剧照
    base_url = 'https://cn.bing.com'
    res = requests.get(url=base_url+f'/images/search?q={q}&qft=+filterui:imagesize-wallpaper+filterui:aspect-wide&form=IRFLTR&first=1&tsc=ImageHoverTitle', headers=header)
    
    res.encoding = res.apparent_encoding
    data = res.content.decode('utf-8', 'ignore')
    
    html = etree.HTML(data)
    
    conda_list = html.xpath('//a[@class="iusc"]/@m')    
    
    # return jsonify(conda_list), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}
    
    cover = re.search('"murl":"(.*?)"', conda_list[0]).group(1)
    if(re.match('^http.*?tva.*$', cover)):
        cover = 'http://imgs.acg17.com/mw1024/'+re.search('^http.*?tva.*?large\/(.*)$', cover).group(1)
    
    cover_1 = re.search('"murl":"(.*?)"', conda_list[1]).group(1)
    if(re.match('^http.*?tva.*$', cover_1)):
        cover_1 = 'http://imgs.acg17.com/mw1024/'+re.search('^http.*?tva.*?large\/(.*)$', cover_1).group(1)
    
    
    # 截取长度的一般进行搜索
    base_url = 'https://bangumi.tv'
    
    res = requests.get(url=base_url+f'/subject_search/{q}?cat=2', headers=header)
    res.encoding = 'utf-8'
    tree = etree.HTML(res.text)
    try: page = tree.xpath('//*[@id="browserItemList"]/li/a/@href')[0]
    except: return jsonify({'tags': None, 'score': None, 'characters': None, 'cover': [cover, cover_1]}), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}
    
    res = requests.get(url=base_url+page, headers=header)
    res.encoding = 'utf-8'
    tree = etree.HTML(res.text)
    # tags
    tags = tree.xpath('//*[@id="subject_detail"]/div[3]/div/a/span/text()')
    
    # 评分
    score = ''
    try: score = tree.xpath('//*[@class="global_score"]/span[0]/text')[0]
    except: pass
    
    # 角色
    characters = []
    try: chas = tree.xpath('//*[@id="browserItemList"]/li/div')
    except: return jsonify({'tags': tags, 'score': score, 'characters': None, 'cover': [cover, cover_1]}), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}
    for cha in chas:
        try: name = cha.xpath('./div/span/span/text()')[0]
        except: name = cha.xpath('./strong/a/@title')[0]
        face = 'https:'+cha.xpath('./strong/a/span/span/@style')[0][22:-2]
        try: cv = cha.xpath('./div/span/a/text()')[0]
        except: cv = None
        characters.append({'name': name, 'face': face, 'cv': cv})
    
    return jsonify({'tags': tags, 'score': score, 'characters': characters, 'cover': [cover, cover_1]}), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}
```

**Comment by IOSYuan** [comment]
搜噶 可惜我不会 Python 感谢你的回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月28日(星期四) 下午4:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Satoing/sakana-acg] 后端开源 (Issue #3)





 
其实后端就是一个python爬虫，只有一个文件，而且写的很烂😂
 涉及到的代码就是下面这些，http框架用的是python的flask。
 @app.route('/acg/<id&gt;') def get_infos(id):     base_url = 'http://agedm1.com/acg/'     header = {         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'     }     res = requests.get(url=base_url+id+'/', headers=header)     res.encoding = 'utf-8'     tree = etree.HTML(res.text)     intro = ***@***.***='detail_imform_desc_pre']/p/text()")[0]     title = ***@***.***='detail_imform_name']/text()")[0]     playlist = ***@***.******@***.***")[0]     img = ***@***.******@***.***')[0]     tags = ***@***.***="container"]/div[4]/div[2]/div/div/ul/li[5]/span[2]/a/text()')     print(tags)          info = {'title': title, 'intro': intro, 'playlist': playlist, 'img': img, 'tags': tags}          return jsonify(info), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"} @app.route('/acg/search') def search():     q = request.args.get('q')     url = 'http://159.75.0.62:11234/ssszz.php?top=10&amp;q={q}&amp;dect=0'     header = {         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'     }     query = {'top':10, 'q': q, 'dect': 0}     res = requests.get(url=url, headers=header, params=query)     res.encoding = 'utf-8'     return res.text, 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"} @app.route('/bangumi') def bangumi():     q = request.args.get('q')     if(len(q) &gt;= 7): q = q[:math.ceil(len(q)//2)]     if(re.match('.*?第.{0,2}', q)):         q = re.search('(.*?)第.{0,2}', q).group(1)     header = {         'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'     }     # 获取剧照     base_url = 'https://cn.bing.com'     res = requests.get(url=base_url+f'/images/search?q={q}&amp;qft=+filterui:imagesize-wallpaper+filterui:aspect-wide&amp;form=IRFLTR&amp;first=1&amp;tsc=ImageHoverTitle', headers=header)          res.encoding = res.apparent_encoding     data = res.content.decode('utf-8', 'ignore')          html = etree.HTML(data)          conda_list = ***@***.******@***.***')              # return jsonify(conda_list), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}          cover = re.search('"murl":"(.*?)"', conda_list[0]).group(1)     if(re.match('^http.*?tva.*$', cover)):         cover = 'http://imgs.acg17.com/mw1024/'+re.search('^http.*?tva.*?large\/(.*)$', cover).group(1)          cover_1 = re.search('"murl":"(.*?)"', conda_list[1]).group(1)     if(re.match('^http.*?tva.*$', cover_1)):         cover_1 = 'http://imgs.acg17.com/mw1024/'+re.search('^http.*?tva.*?large\/(.*)$', cover_1).group(1)               # 截取长度的一般进行搜索     base_url = 'https://bangumi.tv'          res = requests.get(url=base_url+f'/subject_search/{q}?cat=2', headers=header)     res.encoding = 'utf-8'     tree = etree.HTML(res.text)     try: page = ***@***.******@***.***')[0]     except: return jsonify({'tags': None, 'score': None, 'characters': None, 'cover': [cover, cover_1]}), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}          res = requests.get(url=base_url+page, headers=header)     res.encoding = 'utf-8'     tree = etree.HTML(res.text)     # tags     tags = ***@***.***="subject_detail"]/div[3]/div/a/span/text()')          # 评分     score = ''     try: score = ***@***.***="global_score"]/span[0]/text')[0]     except: pass          # 角色     characters = []     try: chas = ***@***.***="browserItemList"]/li/div')     except: return jsonify({'tags': tags, 'score': score, 'characters': None, 'cover': [cover, cover_1]}), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}     for cha in chas:         try: name = cha.xpath('./div/span/span/text()')[0]         except: name = ***@***.***')[0]         face = ***@***.***')[0][22:-2]         try: cv = cha.xpath('./div/span/a/text()')[0]         except: cv = None         characters.append({'name': name, 'face': face, 'cv': cv})          return jsonify({'tags': tags, 'score': score, 'characters': characters, 'cover': [cover, cover_1]}), 200, {"Content-Type":"application/json", 'Access-Control-Allow-Origin': "*"}
